require 'sqlite3'

begin

  db = SQLite3::Database.open "cars_data.db"
  db.execute "CREATE TABLE IF NOT EXISTS Cars(Id INTEGER PRIMARY KEY,
      Make TEXT, Model TEXT, Color TEXT, Price INT)"
  db.execute "INSERT INTO Cars VALUES(1, 'ford', 'edge', 'silver', 29900)"
  db.execute "INSERT INTO Cars VALUES(2, 'ford', 'edge', 'white', 32900)"
  db.execute "INSERT INTO Cars VALUES(3, 'ford', 'edge', 'black', 34900)"
  db.execute "INSERT INTO Cars VALUES(4, 'ford', 'edge', 'red', 39900)"
  db.execute "INSERT INTO Cars VALUES(5, 'ford', 'fiesta', 'red', 14900)"
  db.execute "INSERT INTO Cars VALUES(6, 'ford', 'fiesta', 'silver', 16900)"
  db.execute "INSERT INTO Cars VALUES(7, 'ford', 'fiesta', 'yellow', 18900)"
  db.execute "INSERT INTO Cars VALUES(8, 'ford', 'fiesta', 'black', 19900)"
  db.execute "INSERT INTO Cars VALUES(9, 'ford', 'fusion', 'black', 24900)"
  db.execute "INSERT INTO Cars VALUES(10, 'ford', 'fusion', 'white', 28900)"
  db.execute "INSERT INTO Cars VALUES(11, 'ford', 'fusion', 'red', 29900)"
  db.execute "INSERT INTO Cars VALUES(12, 'ford', 'fusion', 'blue', 32900)"
  db.execute "INSERT INTO Cars VALUES(13, 'ford', 'f150', 'silver', 24900)"
  db.execute "INSERT INTO Cars VALUES(14, 'ford', 'f150', 'black', 34900)"
  db.execute "INSERT INTO Cars VALUES(15, 'ford', 'f150', 'red', 36900)"
  db.execute "INSERT INTO Cars VALUES(16, 'ford', 'f150', 'grey', 42900)"
  db.execute "INSERT INTO Cars VALUES(17, 'ford', 'mustang', 'red', 29900)"
  db.execute "INSERT INTO Cars VALUES(18, 'ford', 'mustang', 'silver', 32900)"
  db.execute "INSERT INTO Cars VALUES(19, 'ford', 'mustang', 'yellow', 39900)"
  db.execute "INSERT INTO Cars VALUES(20, 'ford', 'mustang', 'black', 44900)"
  db.execute "INSERT INTO Cars VALUES(21, 'ford', 'edge', 'blue', 36900)"
  db.execute "INSERT INTO Cars VALUES(22, 'ford', 'edge', 'green', 42900)"
  db.execute "INSERT INTO Cars VALUES(23, 'ford', 'fiesta', 'white', 20900)"
  db.execute "INSERT INTO Cars VALUES(24, 'ford', 'fiesta', 'blue', 15900)"
  db.execute "INSERT INTO Cars VALUES(25, 'ford', 'fusion', 'silver', 29900)"
  db.execute "INSERT INTO Cars VALUES(26, 'ford', 'fusion', 'green', 30900)"
  db.execute "INSERT INTO Cars VALUES(27, 'ford', 'f150', 'white', 29900)"
  db.execute "INSERT INTO Cars VALUES(28, 'ford', 'f150', 'blue', 45900)"
  db.execute "INSERT INTO Cars VALUES(29, 'ford', 'mustang', 'white', 34900)"
  db.execute "INSERT INTO Cars VALUES(30, 'ford', 'mustang', 'orange', 49900)"
  db.execute "INSERT INTO Cars VALUES(31, 'ford', 'edge', 'silver', 33900)"
  db.execute "INSERT INTO Cars VALUES(32, 'ford', 'edge', 'white', 25900)"
  db.execute "INSERT INTO Cars VALUES(33, 'ford', 'edge', 'black', 38900)"
  db.execute "INSERT INTO Cars VALUES(34, 'ford', 'edge', 'red', 45900)"
  db.execute "INSERT INTO Cars VALUES(35, 'ford', 'fiesta', 'red', 17900)"
  db.execute "INSERT INTO Cars VALUES(36, 'ford', 'fiesta', 'silver', 18900)"
  db.execute "INSERT INTO Cars VALUES(37, 'ford', 'fiesta', 'yellow', 19900)"
  db.execute "INSERT INTO Cars VALUES(38, 'ford', 'fiesta', 'black', 16900)"
  db.execute "INSERT INTO Cars VALUES(39, 'ford', 'fusion', 'black', 28900)"
  db.execute "INSERT INTO Cars VALUES(40, 'ford', 'fusion', 'white', 33900)"
  db.execute "INSERT INTO Cars VALUES(41, 'ford', 'fusion', 'red', 35900)"
  db.execute "INSERT INTO Cars VALUES(42, 'ford', 'fusion', 'blue', 27900)"
  db.execute "INSERT INTO Cars VALUES(43, 'ford', 'f150', 'silver', 34900)"
  db.execute "INSERT INTO Cars VALUES(44, 'ford', 'f150', 'black', 38900)"
  db.execute "INSERT INTO Cars VALUES(45, 'ford', 'f150', 'red', 26900)"
  db.execute "INSERT INTO Cars VALUES(46, 'ford', 'f150', 'grey', 32900)"
  db.execute "INSERT INTO Cars VALUES(47, 'ford', 'mustang', 'red', 39900)"
  db.execute "INSERT INTO Cars VALUES(48, 'ford', 'mustang', 'silver', 28900)"
  db.execute "INSERT INTO Cars VALUES(49, 'ford', 'mustang', 'yellow', 44900)"
  db.execute "INSERT INTO Cars VALUES(50, 'ford', 'mustang', 'black', 32900)"
  db.execute "INSERT INTO Cars VALUES(51, 'ford', 'edge', 'blue', 33900)"
  db.execute "INSERT INTO Cars VALUES(52, 'ford', 'edge', 'green', 34900)"
  db.execute "INSERT INTO Cars VALUES(53, 'ford', 'fiesta', 'white', 22900)"
  db.execute "INSERT INTO Cars VALUES(54, 'ford', 'fiesta', 'blue', 18900)"
  db.execute "INSERT INTO Cars VALUES(55, 'ford', 'fusion', 'silver', 32900)"
  db.execute "INSERT INTO Cars VALUES(56, 'ford', 'fusion', 'green', 28900)"
  db.execute "INSERT INTO Cars VALUES(57, 'ford', 'f150', 'white', 34900)"
  db.execute "INSERT INTO Cars VALUES(58, 'ford', 'f150', 'blue', 35900)"
  db.execute "INSERT INTO Cars VALUES(59, 'ford', 'mustang', 'white', 28900)"
  db.execute "INSERT INTO Cars VALUES(60, 'ford', 'mustang', 'orange', 39900)"

rescue SQLite3::Exception => e

  puts "Exception occurred"
  puts e

ensure
  db.close if db
end
