$cars = [
  ["ford", "escape", "red", "15K", "Compact SUV"],
  ["ford", "escape", "black", "15K", "Compact SUV"],
  ["ford", "escape", "white", "15K", "Compact SUV"],
  ["ford", "escape", "red", "20K", "Compact SUV"],
  ["ford", "escape", "black", "20K", "Compact SUV"],
  ["ford", "escape", "white", "20K", "Compact SUV"],
  ["ford", "escape", "red", "25K", "Compact SUV"],
  ["ford", "escape", "black", "25K", "Compact SUV"],
  ["ford", "escape", "white", "25K", "Compact SUV"],
  ["ford", "focus", "red", "15K", "Hatchback"],
  ["ford", "focus", "black", "15K", "Hatchback"],
  ["ford", "focus", "white", "15K", "Hatchback"],
  ["ford", "focus", "red", "20K", "Hatchback"],
  ["ford", "focus", "black", "20K", "Hatchback"],
  ["ford", "focus", "white", "20K", "Hatchback"],
  ["ford", "focus", "red", "25K", "Hatchback"],
  ["ford", "focus", "black", "25K", "Hatchback"],
  ["ford", "focus", "white", "25K", "Hatchback"],
  ["ford", "fiesta", "red", "15K", "Compact"],
  ["ford", "fiesta", "black", "15K", "Compact"],
  ["ford", "fiesta", "white", "15K", "Compact"],
  ["ford", "fiesta", "red", "20K", "Compact"],
  ["ford", "fiesta", "black", "20K", "Compact"],
  ["ford", "fiesta", "white", "20K", "Compact"],
  ["ford", "fiesta", "red", "25K", "Compact"],
  ["ford", "fiesta", "black", "25K", "Compact"],
  ["ford", "fiesta", "white", "25K", "Compact"],
  ["chevy", "camaro", "red", "15K", "Coupe"],
  ["chevy", "camaro", "black", "15K", "Coupe"],
  ["chevy", "camaro", "white", "15K", "Coupe"],
  ["chevy", "camaro", "red", "20K", "Coupe"],
  ["chevy", "camaro", "black", "20K", "Coupe"],
  ["chevy", "camaro", "white", "20K", "Coupe"],
  ["chevy", "camaro", "red", "25K", "Coupe"],
  ["chevy", "camaro", "black", "25K", "Coupe"],
  ["chevy", "camaro", "white", "25K", "Coupe"],
  ["chevy", "impala", "red", "15K", "Sedan"],
  ["chevy", "impala", "black", "15K", "Sedan"],
  ["chevy", "impala", "white", "15K", "Sedan"],
  ["chevy", "impala", "red", "20K", "Sedan"],
  ["chevy", "impala", "black", "20K", "Sedan"],
  ["chevy", "impala", "white", "20K", "Sedan"],
  ["chevy", "impala", "red", "25K", "Sedan"],
  ["chevy", "impala", "black", "25K", "Sedan"],
  ["chevy", "impala", "white", "25K", "Sedan"],
  ["chevy", "malibu", "red", "15K", "Sedan"],
  ["chevy", "malibu", "black", "15K", "Sedan"],
  ["chevy", "malibu", "white", "15K", "Sedan"],
  ["chevy", "malibu", "red", "20K", "Sedan"],
  ["chevy", "malibu", "black", "20K", "Sedan"],
  ["chevy", "malibu", "white", "20K", "Sedan"],
  ["chevy", "malibu", "red", "25K", "Sedan"],
  ["chevy", "malibu", "black", "25K", "Sedan"],
  ["chevy", "malibu", "white", "25K", "Sedan"],
]
