$cars = [
  ["escape", "red", "15K", "Compact SUV"],
  ["escape", "black", "15K", "Compact SUV"],
  ["escape", "white", "15K", "Compact SUV"],
  ["escape", "red", "20K", "Compact SUV"],
  ["escape", "black", "20K", "Compact SUV"],
  ["escape", "white", "20K", "Compact SUV"],
  ["escape", "red", "25K", "Compact SUV"],
  ["escape", "black", "25K", "Compact SUV"],
  ["escape", "white", "25K", "Compact SUV"],
  ["focus", "red", "15K", "Hatchback"],
  ["focus", "black", "15K", "Hatchback"],
  ["focus", "white", "15K", "Hatchback"],
  ["focus", "red", "20K", "Hatchback"],
  ["focus", "black", "20K", "Hatchback"],
  ["focus", "white", "20K", "Hatchback"],
  ["focus", "red", "25K", "Hatchback"],
  ["focus", "black", "25K", "Hatchback"],
  ["focus", "white", "25K", "Hatchback"],
  ["fiesta", "red", "15K", "Compact"],
  ["fiesta", "black", "15K", "Compact"],
  ["fiesta", "white", "15K", "Compact"],
  ["fiesta", "red", "20K", "Compact"],
  ["fiesta", "black", "20K", "Compact"],
  ["fiesta", "white", "20K", "Compact"],
  ["fiesta", "red", "25K", "Compact"],
  ["fiesta", "black", "25K", "Compact"],
  ["fiesta", "white", "25K", "Compact"]
]
